{
  "path": "javax.xml.datatype",
  "name": "DatatypeConfigurationException",
  "values": [
    {
      "type": "ctor",
      "ctor": "<init>()\n            Create a new DatatypeConfigurationException with no specified detail message and cause."
    },
    {
      "type": "ctor",
      "ctor": "<init>(message: String!)\n            Create a new DatatypeConfigurationException with the specified detail message."
    },
    {
      "type": "ctor",
      "ctor": "<init>(message: String!, cause: Throwable!)\n            Create a new DatatypeConfigurationException with the specified detail message and cause."
    },
    {
      "type": "ctor",
      "ctor": "<init>(cause: Throwable!)\n            Create a new DatatypeConfigurationException with the specified cause."
    },
    {
      "type": "method",
      "status": "public"
    },
    {
      "type": "method",
      "status": "public",
      "keyword": "open",
      "identifier": "Unit",
      "code": "printStackTrace()",
      "desc": "Print the the trace of methods from where the error originated."
    },
    {
      "type": "method",
      "status": "public",
      "keyword": "open",
      "identifier": "Unit",
      "code": "printStackTrace(s: PrintStream)",
      "desc": "Print the the trace of methods from where the error originated."
    },
    {
      "type": "method",
      "status": "public",
      "keyword": "open",
      "identifier": "Unit",
      "code": "printStackTrace(s: PrintWriter)",
      "desc": "Print the the trace of methods from where the error originated."
    }
  ]
}