{
  "path": "junit.framework",
  "name": "TestFailure",
  "values": [
    {
      "type": "ctor",
      "ctor": "<init>(failedTest: Test!, thrownException: Throwable!)\n            Constructs a TestFailure with the given test and exception."
    },
    {
      "type": "method",
      "status": "public"
    },
    {
      "type": "method",
      "status": "public",
      "keyword": "open",
      "identifier": "String",
      "code": "exceptionMessage()",
      "desc": "",
      "symbol": "!"
    },
    {
      "type": "method",
      "status": "public",
      "keyword": "open",
      "identifier": "Test",
      "code": "failedTest()",
      "desc": "Gets the failed test.",
      "symbol": "!"
    },
    {
      "type": "method",
      "status": "public",
      "keyword": "open",
      "identifier": "Boolean",
      "code": "isFailure()",
      "desc": ""
    },
    {
      "type": "method",
      "status": "public",
      "keyword": "open",
      "identifier": "Throwable",
      "code": "thrownException()",
      "desc": "Gets the thrown exception.",
      "symbol": "!"
    },
    {
      "type": "method",
      "status": "public",
      "keyword": "open",
      "identifier": "String",
      "code": "toString()",
      "desc": "Returns a short description of the failure."
    },
    {
      "type": "method",
      "status": "public",
      "keyword": "open",
      "identifier": "String",
      "code": "trace()",
      "desc": "",
      "symbol": "!"
    }
  ]
}